# Generated by Django 5.0.1 on 2024-01-29 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News_article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=256, verbose_name='заголовое новости')),
                ('news_text', models.TextField(verbose_name='текст новости')),
                ('news_date', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
            ],
        ),
        migrations.CreateModel(
            name='News_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_author', models.CharField(max_length=256, verbose_name='имя автора')),
                ('comment_text', models.TextField(verbose_name='текст комментария')),
                ('comment_date', models.DateTimeField(auto_now_add=True, verbose_name='дата комментария')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.news_article')),
            ],
        ),
    ]
